# Generated by Django 2.2.2 on 2019-06-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_userprofileinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='chatbtwn',
            field=models.TextField(blank=True, null=True),
        ),
    ]
