# Generated by Django 2.2.2 on 2019-06-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_chatbtwn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='chatbtwn',
            field=models.TextField(),
        ),
    ]
